### ISSUE TITLE
End of sliding sound isn't properly predicted

### ISSUE THREAD

**Issue by thecraftianman** [ZenkakuHiragana/sliding_ability#2]
During a lag spike, the sliding sound has a relatively common tendency to not get stopped correctly and continue looping on the player forever until they run stopsound. This has been happening for many months now, so it's likely not due to the most recent update.

Tested this on a dedicated server

**Comment by ZenkakuHiragana** [comment]
Is there any stable way to reproduce it?  I couldn't figure out how to do it.

**Comment by thecraftianman** [comment]
I'm not sure. It shows up inconsistently, and the only consistent thing I've noticed is that the client usually stutters a bit when it occurs.
